4us more songs
Morten-Moeller/capstone-project pull request #9
Opened 2021-06-10 21:17 UTC by Morten-Moeller

A whole lot of logic for my playlist handling. 
Unfortunately the game does not work in vercel. Tomorrow I have to take care of the backend so that the game runs again.

2021-06-10 22:38 UTC, badabam requested changes
Well done! You do complex things here. It's late for me today, so I might be wrong - **but** you you use a lot of useEffects here. You can probably get rid of a few. Ask yourself: "Am I doing a side effect in here?". If not, you just need a const with some calculated value. 

Looking forward to your updates!

2021-06-10 22:38 UTC, badabam commented on src/App.js
> +  const { newUrl, answers, nextSong } = usePlaylist(playlist)
Maybe `randomUrl` fits better? Why "new"?

2021-06-10 22:38 UTC, badabam commented on src/App.js
> +  const { songUrl, toggle, stop, playing, duration } = useAudio()
Right now I am confused. Another url? What's the difference to the url from your other custom hook?

2021-06-10 22:38 UTC, badabam commented on src/App.js
> +  const { newUrl, answers, nextSong } = usePlaylist(playlist)
`nextSong` does not sound like a function. I'd prefer it to start with a verb.

2021-06-10 22:38 UTC, badabam commented on src/App.js
> +  }, [answers])
It looks to me like you can spare a state and an effect. 

```suggestion
  const [newAnswers, setNewAnswers] = useState(answers)
const loaded = !!answers
```

2021-06-10 22:38 UTC, badabam commented on src/App.js
> +      {loaded && (
Could also just be
```suggestion
      {answers && (
```

2021-06-10 22:38 UTC, badabam commented on src/App.js
> +          answers={newAnswers ? newAnswers : answers}
```suggestion
          answers={newAnswers || answers}
```

2021-06-10 22:38 UTC, badabam commented on src/App.js
> +  }, [playing])
From the dependencies and what you do when they change, I have the feeling that this might be buggy. Please check again - or meet me in the QA channel. 😄

2021-06-10 22:38 UTC, badabam commented on src/App.js
> +    if (showAnswer && !playing) {
Those are both booleans, but they are written in a different style. `showAnswer` sounds like a function.

2021-06-10 22:38 UTC, badabam commented on src/hooks/usePlayList.js
> +    ).then(data => {
Please extract this into a service function to clean up a bit.

2021-06-10 22:38 UTC, badabam commented on src/hooks/usePlayList.js
> +      })
```suggestion
      const cleanPlaylistData = newPlaylistData.filter(el => !!el)
```

2021-06-10 22:38 UTC, badabam commented on src/hooks/usePlayList.js
> +        .then(res => res.json())
Please extract this to `services/searchByArtist` or similar.

2021-06-10 22:38 UTC, badabam commented on src/hooks/usePlayList.js
> +              }
Your if and else if both return the same.

2021-06-10 22:38 UTC, badabam commented on src/hooks/usePlayList.js
> +    if (counter) {
You could do an "early out" here to prevent nesting of everything below.

2021-06-10 22:38 UTC, badabam commented on src/hooks/usePlayList.js
> +  //set all answers and shuffel
*shuffle

2021-06-10 22:38 UTC, badabam commented on src/hooks/usePlayList.js
> +  }, [playlistData, counter])
There is no side effect happening here. You don't need useEffect for this - and you don't need the state `newUrl`. Just a const.

2021-06-10 22:38 UTC, badabam commented on src/hooks/usePlayList.js
> +  }
Please extract to `utils/shuffle Array.js` or similar.

2021-06-11 09:07 UTC, Morten-Moeller commented on src/App.js
> +  const { songUrl, toggle, stop, playing, duration } = useAudio()
This hand the newUrl generated by usePlaylist to the useAudio, to generate a new audio element.I will look at it again and improve the wording

2021-06-11 09:07 UTC, Morten-Moeller commented on src/hooks/usePlayList.js
> +      })
Very nice, i forgot about `!!`

2021-06-11 09:07 UTC, Morten-Moeller commented on src/hooks/usePlayList.js
> +    ).then(data => {
I tried it, but unfortunately it changes the location from where the requests go out and the CORS header then throws a wrench in the works. I note the comment and will implement it immediately after the backend.

2021-06-11 20:03 UTC, merged